version: '3.5'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        MONGO_URI: ${MONGO_URI}
        MONGO_DATABASE: ${MONGO_DATABASE}
        MONGO_POOL_MIN: ${MONGO_POOL_MIN}
        MONGO_POOL_MAX: ${MONGO_POOL_MAX}
        MONGO_MAX_IDLE_TIME_SECOND: ${MONGO_MAX_IDLE_TIME_SECOND}
    container_name: ordent-api
    ports:
      - 4000:4000
    depends_on:
      - database
    networks:
      mynet:

  database:
    container_name: ordent-database
    image: mongo
    volumes:
      - mongoVolume:/data/db
    networks:
      mynet:

volumes:
  mongoVolume:

networks:
  mynet:
